pipeline {
    agent any

    stages {
        stage("Checkout Repo"){
            steps{
                  echo "Hello welcome to the python microservice !"
            }
        }
        stage("Run the Ansible"){
                    steps{
                          echo "Hello welcome to the python microservice !"
                    }
                }

    }

}